(defpackage #:org.shirakumo.fraf.resvg.cffi
  (:use #:cl)
  (:shadow
   #:error)
  (:export
   #:libresvg
   #:error
   #:image-rendering
   #:shape-rendering
   #:text-rendering
   #:transform
   #:size
   #:size-width
   #:size-height
   #:rect
   #:rect-x
   #:rect-y
   #:rect-width
   #:rect-height
   #:init-log
   #:create-options
   #:set-resources-dir
   #:set-dpi
   #:set-font-family
   #:set-font-size
   #:set-serif-family
   #:set-sans-serif-family
   #:set-cursive-family
   #:set-fantasy-family
   #:set-monospace-family
   #:set-languages
   #:set-shape-rendering-mode
   #:set-text-rendering-mode
   #:set-image-rendering-mode
   #:load-font-data
   #:load-font-file
   #:load-system-fonts
   #:destroy-options
   #:parse-from-file
   #:parse-from-data
   #:image-empty-p
   #:image-size
   #:image-viewbox
   #:image-bbox
   #:node-exists-p
   #:node-transform
   #:node-bbox
   #:node-stroke-bbox
   #:destroy-tree
   #:render
   #:render-node))

(defpackage #:org.shirakumo.fraf.resvg
  (:use #:cl)
  (:local-nicknames
   (#:resvg #:org.shirakumo.fraf.resvg.cffi))
  (:export
   #:resvg-error
   #:code
   #:init
   #:load-font
   #:shutdown
   #:image
   #:make-image
   #:free
   #:empty-p
   #:viewbox
   #:size
   #:bbox
   #:node-p
   #:transform
   #:render
   #:with-image
   #:make-transform))
